### PR TITLE
Create get_auth_code.sh

### PR DESCRIPTION
**Pull request by Cinemacloud**
Corresponds to login_puppet.js

### CODE REVIEW

**Review by Cinemacloud — COMMENTED** [review]
Left pherzohlc on lines 18 & 21, can change string to $U

**Comment by astrada** [comment]
Unfortunately, it looks like Google will block Google Account sign-ins from all embedded frameworks starting on January 4, 2021 (https://developers.googleblog.com/2020/08/guidance-for-our-effort-to-block-less-secure-browser-and-apps.html).

**Comment by Cinemacloud** [comment]
Alessandro, they've already been doing this on other platforms like Google Cloud and there are workarounds to make it undetectable via stealth mode of Puppeteer.

**Comment by Cinemacloud** [comment]
Alessandro, interesting but they've already been doing this on other platform flows like Google Cloud and there are workarounds to make it undetectable via stealth mode plugin of Puppeteer. 

And the link you provided said they're targetting CEF and 'other non-suopported browsers. Puppeteer just uses a standard Chromium distribution not CEF and will remain supported as not vulnerable to MITM attack's they're trying to protect.

**Comment by Cinemacloud** [comment]
Alessandro, interesting but they've already been doing this on other platform flows like Google Cloud and there are workarounds to make it undetectable via the stealth-mode plugin of Puppeteer. 

And the link you provided said they're targetting CEF and 'other non-supported browsers. Puppeteer uses a standard Chromium distribution not CEF and will remain supported as not vulnerable to MITM attacks they're trying to protect.

**Comment by Cinemacloud** [comment]
Alessandro, interesting but they've already been doing this on other platform flows like Google Cloud and there are workarounds to make it undetectable via the stealth-mode plugin of Puppeteer. 

And the link you provided said they're targetting CEF and 'other non-supported browsers.' Puppeteer uses a standard Chromium distribution not CEF and will remain supported as not vulnerable to MITM attacks they're trying to protect.

**Comment by astrada** [comment]
All right, thanks for your contribution!

**Comment by Cinemacloud** [comment]
.. noticed you committed the get_auth_code.sh but didn't look at the comment I made above "[accidentally] left pherzohlc on lines 18 & 21, can change string to $U"  -- thanks Alessandro

**Comment by astrada** [comment]
OK

**Pull request merged**
